import type { Metadata } from "next";
import { Anek_Bangla } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";
import BreakingNews from "@/components/Shared/BreakingNews";

const anekBangla = Anek_Bangla({
  variable: "--font-anek-bangla",
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${anekBangla.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        <BreakingNews />
        {children}
      </body>
    </html>
  );
}
